### ISSUE TITLE
Request for collaboration

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/ddclient#1]
The original project at `https://github.com/ddclient/ddclient` has been archived, so those of us offering to take it over can no longer discuss things on its issue tracker.

As mentioned in https://github.com/ddclient/ddclient/issues/528#issuecomment-1588382580 I am happy to take on the project. Since upstream has now been discontinued, I will definitely maintain the project for my own use short-term. If there's sufficient interest from e.g. packagers and collaborators, I'll be happy to maintain it longer-term too.

Why use my fork? I don't have particular expertise in DNS, but I'm a long-term user of `ddclient`, and I have a history of taking other unmaintained projects and maintaining them for a long time, e.g.:

* https://github.com/AbiWord/enchant 
* https://github.com/rrthomas/recode
* https://github.com/rrthomas/mmv

The previous maintainer of ddclient rightly pointed out that the code base is not in a great state, and recommended that others use a different dynamic DNS client, so why continue with ddclient?

* Because it's familiar
* Because it supports a huge range of dynamic DNS providers.

Others have suggested rewriting ddclient in a more modern language than Perl. I sympathise with this aim; indeed, I have rewritten other projects that I have taken on, but I don't think it's a great idea for ddclient; at least, I don't have the time. Instead, if I find there is interest in my fork, I plan to make some radical simplifications to make `ddclient` more maintainable long-term:

* [X] Remove support for finding IP address via many different routers. Quite simply, because I have never needed this myself.
* [X] Remove duplicate support for internet communication: use curl, rather than `WWW::Curl::Easy` or the non-Curl code.
* [x] Remove out-of-date/duplicate providers.

In general, I will concentrate on the core functionality of updating dynamic DNS entries, and tend to remove everything else, while retaining backwards compatibility on the command-line and in config files. In short, I will try to keep things working as well as I can for existing users.

**Comment by LenardHess** [comment]
As mentioned in the ddclient issue, I'm also up for maintenance of this project.

I share your opinion of getting ddclient simplified. My prior ideas for this were:
- Deprecating the sendmail failure notification by replacing it with a generic external command option.
- Section off the providers logic to ease adding, updating or deprecating individual providers

**Comment by LenardHess** [comment]
@wimpunk (following up on [here](https://github.com/ddclient/ddclient/issues/528#issuecomment-1600386826))
How much time until ddclient.net has to be renewed? What are the costs of the domain (or any other infrastructure used for ddclient)?

**Comment by rrthomas** [comment]
> As mentioned in the ddclient issue, I'm also up for maintenance of this project.
> 
> I share your opinion of getting ddclient simplified. My prior ideas for this were:
> 
>     * Deprecating the sendmail failure notification by replacing it with a generic external command option.
> 
>     * Section off the providers logic to ease adding, updating or deprecating individual providers

These ideas sound entirely complementary to mine, that's great. If you're happy to start development on my fork for now, I could add you as a collaborator.

As you will see, the one change I've made so far is to merge DNSExit v2 API support (it's something I needed). Of course, it will be necessary to go to the archived project and find important fixes and updates there to merge.

**Comment by LenardHess** [comment]
I'd be up to start, yes

I already resubmitted #2  for the feature I wanted to add originally.

**Comment by rrthomas** [comment]
I would be happy to give you maintainer access to this repo so we can move faster, if you like. I have updated the code header with just my details as maintainer; feel free to add your own.

**Comment by nemchik** [comment]
LSIO maintainer here. We are considering deprecating https://github.com/linuxserver/docker-ddclient but given your fork, we'll keep an eye on things for a little while before taking any action.

**Comment by LenardHess** [comment]
I sure hope the LSIO container sticks around, as I've been using it for my ddclient setup ;)

I was planning on reaching out to you guys anyways in the coming days, to figure out whether you guys would want to transition, and if, how to make it easiest for all of us.

But first I'd say we should figure out what happens to ddclient.net and the ddclient github organization

**Comment by nemchik** [comment]
> But first I'd say we should figure out what happens to ddclient.net and the ddclient github organization

Ping me once you've got those things sorted and a [release](https://github.com/rrthomas/ddclient/releases) tagged.

**Comment by rrthomas** [comment]
@LenardHess I've pushed a couple of big code-removal commits, but since the first one (#5) causes test failures, I'll obviously work on that first, and before that I'll fix CI.

**Comment by tomeon** [comment]
> As for codebase TLC goals, what do you think about this?:
>
> - Implement code coverage for tests (via, e.g., [`Devel::Cover`](https://metacpan.org/pod/Devel::Cover))
> - Add tests for more providers (possibly with mocked-up provider APIs)?

More tests would be great.

**Comment by LenardHess** [comment]
@tomeon 
> In case it proves infeasible to adopt the https://github.com/ddclient GitHub organization, I've created the organization https://github.com/ddclient-ng. If you'd like to coordinate work there, I'd be most happy to add you and other collaborators to the organization. I can turn it over its ownership to you as well, as I can't pretend that I'll be able to devote more than avocational attention to the project.

I've reached out about the future of the ddclient.net domain, I didn't yet get around to doing so for the Github organization.
 
> As for codebase TLC goals, what do you think about this?:
> 
>     * Implement code coverage for tests (via, e.g., [`Devel::Cover`](https://metacpan.org/pod/Devel::Cover))
> 
>     * Add tests for more providers (possibly with mocked-up provider APIs)?

Sounds good, I was also thinking about getting mock providers set up for testing. At minimum we should have better docs on what the expected API responses are.

**Comment by wimpunk** [comment]
> @wimpunk (following up on [here](https://github.com/ddclient/ddclient/issues/528#issuecomment-1600386826)) How much time until ddclient.net has to be renewed? What are the costs of the domain (or any other infrastructure used for ddclient)?

It has to be renewed on the 19th of August. I can transfer the ownership if needed. It's currently hosted by one.com but any DNS provider offering the .net domain should work.  It currently costs me 51Euro.

Did @SuperSandro2000 told why he wanted to archive the project in stead of transferring the ownership?  Maybe it's just easier to transfer the project, no?

**Comment by wimpunk** [comment]
@LenardHess , I can transfer the ownership of the ddlcient organisation if needed.

**Comment by LenardHess** [comment]
> It has to be renewed on the 19th of August. I can transfer the ownership if needed. It's currently hosted by one.com but any DNS provider offering the .net domain should work. It currently costs me 51Euro.

Is one.com just the registrar or also the website host? 51€ per year I assume?
 
> Did @SuperSandro2000 told why he wanted to archive the project in stead of transferring the ownership? Maybe it's just easier to transfer the project, no?

I did not specifically reach out to him so far. He closed down (archived) the repo even though both @rrthomas and I offered to take over within the [other conversation](https://github.com/ddclient/ddclient/issues/528), but i neither asked specifically about taking over the organization nor did he state to us any reason why he closed instead of transferring.

**Comment by LenardHess** [comment]
> @LenardHess , I can transfer the ownership of the ddlcient organisation if needed.

Sure, that would be great.

**Comment by tomeon** [comment]
> I've reached out about the future of the ddclient.net domain, I didn't yet get around to doing so for the Github organization.

It's a moot point now that it looks like ownership of the ddclient organization will be transferred, but I brought this up because one of the previous contributors seemed to [express reluctance to hand it over](https://github.com/ddclient/ddclient/issues/528#issuecomment-1620384301) ("Some things need to end for good and I am somewhat relieved ddclient is one of them," ouch).  I am glad that it appears ddclient and its associated GitHub org won't die after all.

> I was also thinking about getting mock providers set up for testing. At minimum we should have better docs on what the expected API responses are.

Cool.  I will see about getting a start on it this weekend.

**Comment by wimpunk** [comment]
> > @LenardHess , I can transfer the ownership of the ddlcient organisation if needed.
> 
> Sure, that would be great.

Looks like I was wrong. I'm no longer part of the team. You'll have to ask @supersandro2000.

**Comment by wimpunk** [comment]
> Is one.com just the registrar or also the website host? 51€ per year I assume?
> 
> >

It's just a registrar. Everything is hosted on github.com and the old stuff is hosted on sf.net.

**Comment by LenardHess** [comment]
> It's just a registrar. Everything is hosted on github.com and the old stuff is hosted on sf.net.

Ok, seeing as the docs repo is also archived right now we might have to fork that and redirect to the fork, depending on what happens to the github organization.

Lets switch to E-Mail to take care of the domain transfer.

**Comment by LenardHess** [comment]
> > > @LenardHess , I can transfer the ownership of the ddlcient organisation if needed.
> > 
> > 
> > Sure, that would be great.
> 
> Looks like I was wrong. I'm no longer part of the team. You'll have to ask @SuperSandro2000.

@SuperSandro2000 (@DaveSophoServices @rhansen):
Can you please add myself and/or @rrthomas to the ddclient organization?

**Comment by rrthomas** [comment]
If it helps, I'm a member of the organization already.

**Comment by LenardHess** [comment]
> I can't see you in the [organization people list](https://github.com/orgs/ddclient/people)?

I can see myself. (Edit: It was a "private" status; I made it public.)

> Are you able to unarchive the org and repo?

No, presumably because my role is just "member".

> I would prefer to merge this fork back into the original repo if we can keep the original org alive.

Absolutely!

**Comment by LenardHess** [comment]
@rrthomas please just respond with a message instead of editing mine with a response, its confusing and not giving me a notification

**Comment by rrthomas** [comment]
> @rrthomas please just respond with a message instead of editing mine with a response, its confusing and not giving me a notification

Apologies, I thought I had undone that! I hit Edit rather than Quote Reply by mistake.

**Comment by SuperSandro2000** [comment]
> Can you please add myself and/or @rrthomas to the ddclient organization?

done

**Comment by rrthomas** [comment]
> > Can you please add myself and/or @rrthomas to the ddclient organization?
> 
> done

Thanks, is it OK if I unarchive the project now?

**Comment by rrthomas** [comment]
I have unarchived the ddclient/ddclient project.

**Comment by rrthomas** [comment]
Closing issue as done: we have collaboration, and we're moving back to the original project shortly.
