### ISSUE TITLE
Providers: Fix various old caching issues

### ISSUE THREAD

**Issue by LenardHess** [rrthomas/ddclient#11]
Some providers have improper implementations with regards to caching. It seems that these implementations never did right in the first place.

These fixes are not required for the v3.11 release, that is handled in #10 .

Providers without proper cache parameter implementation:
- [ ] 1984
- [ ] Njalla
- [ ] nsupdate

**Comment by rrthomas** [comment]
Moved to ddclient/ddclient#554.
