### ISSUE TITLE
regfishde: Fix IPv6 support

### ISSUE THREAD

**Issue by LenardHess** [rrthomas/ddclient#12]
regfishde seems to have broken ipv6 support thanks to deleting `$config{$hash}{wantip}` twice:
https://github.com/rrthomas/ddclient/blob/a0f3d1479bad04ea37c1f09bfcc6569bb93d07e2/ddclient.in#L7557-L7558

**Comment by rrthomas** [comment]
Moved to ddclient/ddclient#553.
