### ISSUE TITLE
3.11 release plan

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/ddclient#8]
A quick backwards-compatible release with essential bug-fixes and functionality enhancements only. To-do list:

- [x] Fix caching problems (#3)
- [x] Update changelog
- [ ] Contact downstream package maintainers? (Change of maintainers, change of curl dependency to be required, ...)
- [ ] Merge back into the original repo
- [ ] Set up signed tags (and commits)

**Comment by rrthomas** [comment]
@LenardHess feel free to add items here. I didn't put any code re-org here to keep it minimal, but in theory anything backwards-compatible *could* go here.

**Comment by LenardHess** [comment]
- [x] Update changelog
- [ ] Contact downstream package maintainers? (Change of maintainers, change of curl dependency to be required, ...)
- [ ] Merge back into the original repo
- [ ] Set up signed tags (and commits)

**Comment by nemchik** [comment]
> * [ ]  Update changelog
> * [ ]  Contact downstream package maintainers? (Change of maintainers, change of curl dependency to be required, ...)
> * [ ]  Merge back into the original repo

If you're able to get the original org/repo there won't be any change needed from lsio. Our build process will pick up any release on that repo.

If you end up needing to release from this repo, we'll have to adjust our builds, but that's a very small task. Admittedly we would rather see things continue from the original org/repo, and it does look like that's possible at this point, but if there's hurdles and it ends up not working out we'll discuss it with you. Definitely not in a hurry to define any recommendations or requirements from our end until the dust settles with the org/repo.

**Comment by rrthomas** [comment]
I've made a PR to re-merge into ddclient/ddclient. Assuming that's OK, I will move the remaining issues there from this repo once I've merged the PR.

**Comment by rrthomas** [comment]
Moved to ddclient/ddclient#552.
